apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.deployment.image.name }}:{{ .Values.image_tag }}
        ports:
        - containerPort: 8080

#