{{ if eq .Values.environment "dev" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: promote-vonage-scheduler
          image: kinluek/envpromoter:1.0.5
          args:
            - "-github-user=$(GITHUB_USERNAME)"
            - "-github-token=$(GITHUB_TOKEN)"
            - "-from-url=https://api.github.com/repos/sichan-vonage/argo-cd-demo-configs/contents/app-configurations/providers/vonage-scheduler/values-dev-image.yaml"
            - "-to-url=https://api.github.com/repos/sichan-vonage/argo-cd-demo-configs/contents/app-configurations/providers/vonage-scheduler/values-prod-image.yaml"
            - "-repo-url=https://api.github.com/repos/sichan-vonage/argo-cd-demo-configs"
          env:
            - name: GITHUB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: github-ci-credential
                  key: username
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-ci-credential
                  key: token
      restartPolicy: Never
  backoffLimit: 0
{{ end }}
